baseURL = 'https://www.green-coding.org/'
languageCode = 'de-en'
title = 'Green-Coding.org'

paginate = 10
paginatePath = "page"

summaryLength = 30

[minify]
  minifyOutput = true

[outputs]
  home = ['HTML', 'CSS']

